// Package help provides CLI help text rendering for kubectl-why.
package help

import (
	"fmt"
	"strings"

	"github.com/alisonui/why-blocked/internal/ui"
)

// PrintGlobalUsage returns the short global help text for kubectl-why (used by --help).
func PrintGlobalUsage() string {
	var b strings.Builder
	b.WriteString("kubectl-why - Explain why a Kubernetes resource was blocked by security rules\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("USAGE") + "\n")
	b.WriteString("  kubectl why [flags] <command> [args]\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("COMMANDS") + "\n")
	b.WriteString("  " + ui.Cyan("explain") + " <resource>        Explain why a resource was blocked\n")
	b.WriteString("  " + ui.Cyan("decision") + " list|get       List or get security decisions\n")
	b.WriteString("  " + ui.Cyan("mock") + " create <name>     Create a mock decision for testing\n")
	b.WriteString("  " + ui.Cyan("help") + " [topic]           Show detailed help for a topic\n")
	b.WriteString("  " + ui.Cyan("version") + "                Show version information\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("COMMON FLAGS") + "\n")
	b.WriteString("  " + ui.Yellow("--dir") + " <path>          Directory for decisions (default: ~/.kubectl-why/decisions)\n")
	b.WriteString("  " + ui.Yellow("--lang") + " <code>         Output language: en, ko, ja, zh, es (auto-detected)\n")
	b.WriteString("  " + ui.Yellow("-o, --output") + " <fmt>     Output format: text, json (default: text)\n")
	b.WriteString("  " + ui.Yellow("--scan") + " <modes>        Enable CVE/SBOM scanners: cve, sbom (requires trivy/syft)\n")
	b.WriteString("  " + ui.Yellow("--ai") + "                 Add AI explanation (requires WHY_AI_API_KEY)\n")
	b.WriteString("  " + ui.Yellow("--quiet") + "              Suppress status messages (keeps warnings/errors)\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("EXAMPLES") + "\n")
	b.WriteString("  " + ui.Dim("# Explain a deployment") + "\n")
	b.WriteString("  kubectl why explain my-app\n")
	b.WriteString("\n")
	b.WriteString("  " + ui.Dim("# Get JSON output") + "\n")
	b.WriteString("  kubectl why -o json explain my-app\n")
	b.WriteString("\n")
	b.WriteString("  " + ui.Dim("# List recent decisions") + "\n")
	b.WriteString("  kubectl why decision list\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("LEARN MORE") + "\n")
	b.WriteString("  kubectl why " + ui.Cyan("help") + "           Show all help topics\n")
	b.WriteString("  kubectl why " + ui.Cyan("help") + " explain    Detailed guide for explain command\n")
	b.WriteString("  kubectl why " + ui.Cyan("help") + " flags      Complete flag reference\n")
	b.WriteString("  kubectl why " + ui.Cyan("help") + " scan       Guide for CVE/SBOM scanning\n")
	b.WriteString("  kubectl why " + ui.Cyan("help") + " ai         Guide for AI enhancement\n")
	b.WriteString("\n")
	return b.String()
}

// PrintMockUsage returns the help text for the 'mock' command.
func PrintMockUsage() string {
	var b strings.Builder
	b.WriteString("Error: 'mock create' requires a resource name\n")
	b.WriteString("\n")
	b.WriteString("Usage:\n")
	b.WriteString("  kubectl why mock create <name>\n")
	b.WriteString("\n")
	b.WriteString("Description:\n")
	b.WriteString("  Create a mock blocked decision for testing purposes.\n")
	b.WriteString("  Useful for testing output formats, translations, and workflows.\n")
	b.WriteString("\n")
	b.WriteString("Examples:\n")
	b.WriteString("  # Create a basic mock decision\n")
	b.WriteString("  kubectl why mock create test-app\n")
	b.WriteString("\n")
	b.WriteString("  # Create mock and immediately view it\n")
	b.WriteString("  kubectl why mock create my-deploy && kubectl why explain my-deploy\n")
	b.WriteString("\n")
	b.WriteString("  # Create mock and view in different language\n")
	b.WriteString("  kubectl why mock create test-svc && kubectl why --lang ja explain test-svc\n")
	b.WriteString("\n")
	b.WriteString("  # Create mock and export as JSON\n")
	b.WriteString("  kubectl why mock create api-gateway && kubectl why -o json explain api-gateway\n")
	b.WriteString("\n")
	return b.String()
}

// PrintDecisionUsage returns the help text for the 'decision' command.
func PrintDecisionUsage() string {
	var b strings.Builder
	b.WriteString("Error: 'decision' requires a subcommand\n")
	b.WriteString("\n")
	b.WriteString("Usage:\n")
	b.WriteString("  kubectl why decision list         List recent security decisions\n")
	b.WriteString("  kubectl why decision get <id>     Get details of a specific decision\n")
	b.WriteString("\n")
	b.WriteString("Examples:\n")
	b.WriteString("  # List recent decisions (up to 10)\n")
	b.WriteString("  kubectl why decision list\n")
	b.WriteString("\n")
	b.WriteString("  # Get specific decision by ID\n")
	b.WriteString("  kubectl why decision get mock-test-1234567890\n")
	b.WriteString("\n")
	b.WriteString("  # Get decision with specific output format\n")
	b.WriteString("  kubectl why -o json decision get dec-7721\n")
	b.WriteString("\n")
	b.WriteString("  # Get decision in another language\n")
	b.WriteString("  kubectl why --lang ko decision get dec-7721\n")
	b.WriteString("\n")
	return b.String()
}

// PrintDecisionGetUsage returns the help text for the 'decision get' command.
func PrintDecisionGetUsage() string {
	var b strings.Builder
	b.WriteString("Error: 'decision get' requires a decision ID\n")
	b.WriteString("\n")
	b.WriteString("Usage:\n")
	b.WriteString("  kubectl why decision get <id> [flags]\n")
	b.WriteString("\n")
	b.WriteString("Description:\n")
	b.WriteString("  Retrieve and display a specific security decision by its ID.\n")
	b.WriteString("  The ID can be found using 'kubectl why decision list'.\n")
	b.WriteString("\n")
	b.WriteString("Examples:\n")
	b.WriteString("  # Get decision with human-readable text output\n")
	b.WriteString("  kubectl why decision get mock-test-1234567890\n")
	b.WriteString("\n")
	b.WriteString("  # Get decision as JSON for processing\n")
	b.WriteString("  kubectl why -o json decision get dec-7721\n")
	b.WriteString("\n")
	b.WriteString("  # Get decision in Korean\n")
	b.WriteString("  kubectl why --lang ko decision get dec-7721\n")
	b.WriteString("\n")
	b.WriteString("  # Get decision in Spanish as JSON\n")
	b.WriteString("  kubectl why --lang es -o json decision get dec-7721\n")
	b.WriteString("\n")
	b.WriteString("Tip: Use 'kubectl why decision list' to see available decision IDs\n")
	b.WriteString("\n")
	return b.String()
}

// PrintExplainUsage returns the help text for the 'explain' command.
func PrintExplainUsage() string {
	var b strings.Builder
	b.WriteString("Error: 'explain' requires a resource name\n")
	b.WriteString("\n")
	b.WriteString("Usage:\n")
	b.WriteString("  kubectl why explain <name> [flags]              (assumes Deployment)\n")
	b.WriteString("  kubectl why explain <kind> <name> [flags]       (explicit kind)\n")
	b.WriteString("\n")
	b.WriteString("Description:\n")
	b.WriteString("  Explain why a Kubernetes resource was blocked by security rules.\n")
	b.WriteString("  This command performs fast, offline static analysis by default.\n")
	b.WriteString("  Use flags to customize output format, language, or enable external scanning.\n")
	b.WriteString("\n")
	b.WriteString("When to Use Optional Features:\n")
	b.WriteString("\n")
	b.WriteString("  --lang <code>\n")
	b.WriteString("    Translate explanations for multilingual teams. Evidence paths and CVE IDs\n")
	b.WriteString("    remain unchanged. Works offline; no AI required.\n")
	b.WriteString("\n")
	b.WriteString("  -o json\n")
	b.WriteString("    Get structured output for automation. Includes schemaVersion for compatibility.\n")
	b.WriteString("    Use for CI/CD, dashboards, or scripting with jq.\n")
	b.WriteString("\n")
	b.WriteString("  --scan cve,sbom\n")
	b.WriteString("    Attach live vulnerability/SBOM data. Requires trivy/syft installed.\n")
	b.WriteString("    Warns if missing; tool continues working. Offline-first default preserved.\n")
	b.WriteString("\n")
	b.WriteString("  --ai\n")
	b.WriteString("    Add AI-generated context (requires API key). CLI works fully without this.\n")
	b.WriteString("    Base explanations are complete; AI provides optional enhancement.\n")
	b.WriteString("\n")
	b.WriteString("Examples:\n")
	b.WriteString("  # Basic usage (assumes Deployment kind)\n")
	b.WriteString("  kubectl why explain my-app\n")
	b.WriteString("\n")
	b.WriteString("  # Explicit resource kind\n")
	b.WriteString("  kubectl why explain deployment my-app\n")
	b.WriteString("  kubectl why explain pod suspicious-pod\n")
	b.WriteString("\n")
	b.WriteString("  # Different output languages\n")
	b.WriteString("  kubectl why --lang ja explain my-app\n")
	b.WriteString("  kubectl why --lang ko explain my-app\n")
	b.WriteString("  kubectl why --lang es explain my-app\n")
	b.WriteString("\n")
	b.WriteString("  # JSON output for automation\n")
	b.WriteString("  kubectl why -o json explain my-app\n")
	b.WriteString("  kubectl why --output json explain my-app | jq '.decision.violations'\n")
	b.WriteString("\n")
	b.WriteString("  # With external vulnerability scanning (requires trivy)\n")
	b.WriteString("  kubectl why --scan cve explain my-app\n")
	b.WriteString("\n")
	b.WriteString("  # With both CVE and SBOM scanning\n")
	b.WriteString("  kubectl why --scan cve,sbom explain my-app\n")
	b.WriteString("\n")
	b.WriteString("  # With AI enhancement (requires WHY_AI_API_KEY)\n")
	b.WriteString("  kubectl why --ai explain my-app\n")
	b.WriteString("\n")
	b.WriteString("  # Combined: JSON output in Korean with CVE scanning\n")
	b.WriteString("  kubectl why --lang ko -o json --scan cve explain my-app\n")
	b.WriteString("\n")
	return b.String()
}

// RenderHelpIndex returns the help index showing all available help topics.
func RenderHelpIndex() string {
	var b strings.Builder
	b.WriteString(ui.Bold(ui.Cyan("kubectl-why Help Topics")) + "\n")
	b.WriteString("\n")
	b.WriteString("Get detailed help for specific topics:\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("COMMANDS") + "\n")
	b.WriteString("  kubectl why " + ui.Cyan("help explain") + "     Explain why resources were blocked\n")
	b.WriteString("  kubectl why " + ui.Cyan("help decision") + "    Manage and query security decisions\n")
	b.WriteString("  kubectl why " + ui.Cyan("help mock") + "        Create test data\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("CONFIGURATION") + "\n")
	b.WriteString("  kubectl why " + ui.Cyan("help flags") + "       All flags and options\n")
	b.WriteString("  kubectl why " + ui.Cyan("help output") + "      Output formats and automation\n")
	b.WriteString("  kubectl why " + ui.Cyan("help i18n") + "        Language support\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("OPTIONAL FEATURES") + "\n")
	b.WriteString("  kubectl why " + ui.Cyan("help scan") + "        CVE and SBOM scanning\n")
	b.WriteString("  kubectl why " + ui.Cyan("help ai") + "          AI-powered insights\n")
	b.WriteString("\n")
	b.WriteString(ui.Yellow("TIP:") + " Use " + ui.Yellow("--help") + " for quick reference.\n")
	b.WriteString("\n")
	return b.String()
}

// RenderHelpExplain returns detailed help for the explain command.
func RenderHelpExplain() string {
	var b strings.Builder
	b.WriteString(ui.Bold(ui.Cyan("kubectl why explain")) + " - Explain blocked resources\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("USAGE") + "\n")
	b.WriteString("  kubectl why explain " + ui.Dim("<name>") + "              " + ui.Dim("# Assumes Deployment") + "\n")
	b.WriteString("  kubectl why explain " + ui.Dim("<kind> <name>") + "       " + ui.Dim("# Explicit kind") + "\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("WHAT IT DOES") + "\n")
	b.WriteString("  Explains why a Kubernetes resource was blocked by security rules.\n")
	b.WriteString("  • Reasoning tool, not a scanner\n")
	b.WriteString("  • Works offline by default (no external dependencies)\n")
	b.WriteString("  • Fast, local static analysis\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("OUTPUT INCLUDES") + "\n")
	b.WriteString("  • Why it was blocked (summary)\n")
	b.WriteString("  • Specific violations with severity levels\n")
	b.WriteString("  • Evidence (field paths, values)\n")
	b.WriteString("  • Fix suggestions (minimal changes needed)\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("QUICK EXAMPLES") + "\n")
	b.WriteString("  kubectl why explain my-app\n")
	b.WriteString("  kubectl why explain pod suspicious-pod\n")
	b.WriteString("  kubectl why " + ui.Yellow("--lang ko") + " explain my-app\n")
	b.WriteString("  kubectl why " + ui.Yellow("-o json") + " explain my-app | jq '.decision.violations'\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("OPTIONAL ENHANCEMENTS") + "\n")
	b.WriteString("  All features work offline. These require external tools/keys:\n")
	b.WriteString("  • " + ui.Yellow("--scan cve,sbom") + "   Attach live CVE/SBOM data (requires trivy/syft)\n")
	b.WriteString("  • " + ui.Yellow("--ai") + "             Add AI context (requires WHY_AI_API_KEY)\n")
	b.WriteString("  • " + ui.Yellow("--lang <code>") + "     Translate output (en, ko, ja, zh, es)\n")
	b.WriteString("  • " + ui.Yellow("-o json") + "           Structured output for automation\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("COMBINED EXAMPLE") + "\n")
	b.WriteString("  kubectl why " + ui.Yellow("--lang ko -o json --scan cve") + " explain my-app\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("EXIT CODES") + " " + ui.Dim("(for automation)") + "\n")
	b.WriteString("  " + ui.Green("0") + " = Decision ALLOWED\n")
	b.WriteString("  " + ui.Yellow("2") + " = Decision BLOCKED (needs attention)\n")
	b.WriteString("  " + ui.Red("1") + " = Runtime error (invalid args, repo error, etc.)\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("LEARN MORE") + "\n")
	b.WriteString("  kubectl why help flags   " + ui.Dim("# All flags") + "\n")
	b.WriteString("  kubectl why help scan    " + ui.Dim("# CVE/SBOM scanning") + "\n")
	b.WriteString("  kubectl why help ai      " + ui.Dim("# AI enhancement") + "\n")
	b.WriteString("\n")
	return b.String()
}

// RenderHelpDecision returns detailed help for the decision command.
func RenderHelpDecision() string {
	var b strings.Builder
	b.WriteString(ui.Bold(ui.Cyan("kubectl why decision")) + " - Query stored decisions\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("USAGE") + "\n")
	b.WriteString("  kubectl why decision list\n")
	b.WriteString("  kubectl why decision get " + ui.Dim("<id>") + "\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("WHAT IT DOES") + "\n")
	b.WriteString("  Security decisions are stored locally when resources are explained.\n")
	b.WriteString("  Query and retrieve them for later analysis.\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("SUBCOMMANDS") + "\n")
	b.WriteString("  " + ui.Cyan("list") + "      Show recent decisions (up to 10)\n")
	b.WriteString("            Columns: timestamp, ID, resource, status, summary\n")
	b.WriteString("\n")
	b.WriteString("  " + ui.Cyan("get <id>") + "  Retrieve specific decision by ID\n")
	b.WriteString("            Supports " + ui.Yellow("--lang") + " and " + ui.Yellow("-o json") + "\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("EXAMPLES") + "\n")
	b.WriteString("  kubectl why decision list\n")
	b.WriteString("  kubectl why decision get mock-test-1234567890\n")
	b.WriteString("  kubectl why " + ui.Yellow("-o json") + " decision get dec-7721\n")
	b.WriteString("  kubectl why " + ui.Yellow("--lang ko") + " decision get dec-7721\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("STORAGE LOCATION") + "\n")
	b.WriteString("  Default: " + ui.Dim("~/.kubectl-why/decisions") + "\n")
	b.WriteString("  Custom:  " + ui.Yellow("--dir") + " " + ui.Dim("<path>") + "\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("LEARN MORE") + "\n")
	b.WriteString("  kubectl why help output  " + ui.Dim("# Output formats") + "\n")
	b.WriteString("  kubectl why help i18n    " + ui.Dim("# Language support") + "\n")
	b.WriteString("\n")
	return b.String()
}

// RenderHelpMock returns detailed help for the mock command.
func RenderHelpMock() string {
	var b strings.Builder
	b.WriteString(ui.Bold(ui.Cyan("kubectl why mock")) + " - Create test data\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("USAGE") + "\n")
	b.WriteString("  kubectl why mock create " + ui.Dim("<name>") + "\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("WHAT IT DOES") + "\n")
	b.WriteString("  Creates a mock blocked decision for testing without real violations.\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("MOCK INCLUDES") + "\n")
	b.WriteString("  • Example violations (privileged container, insecure image)\n")
	b.WriteString("  • Evidence with field paths\n")
	b.WriteString("  • Fix suggestions\n")
	b.WriteString("  • Simulated CVE data\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("EXAMPLES") + "\n")
	b.WriteString("  kubectl why mock create test-app\n")
	b.WriteString("  kubectl why mock create my-deploy && kubectl why explain my-deploy\n")
	b.WriteString("  kubectl why mock create test-svc && kubectl why " + ui.Yellow("--lang ja") + " explain test-svc\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("USE CASES") + "\n")
	b.WriteString("  • Test output formats before CI/CD integration\n")
	b.WriteString("  • Try different languages\n")
	b.WriteString("  • Demo kubectl-why without real violations\n")
	b.WriteString("  • Validate JSON parsing in automation\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("LEARN MORE") + "\n")
	b.WriteString("  kubectl why help explain  " + ui.Dim("# Viewing decisions") + "\n")
	b.WriteString("  kubectl why help output   " + ui.Dim("# Output formats") + "\n")
	b.WriteString("\n")
	return b.String()
}

// RenderHelpFlags returns detailed help for all flags.
func RenderHelpFlags() string {
	var b strings.Builder
	b.WriteString(ui.Bold(ui.Cyan("Flags Reference")) + "\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("BASIC FLAGS") + " " + ui.Dim("(offline, no dependencies)") + "\n")
	b.WriteString("\n")
	b.WriteString("  " + ui.Yellow("--dir") + " " + ui.Dim("<path>") + "\n")
	b.WriteString("    Storage directory for decisions\n")
	b.WriteString("    Default: " + ui.Dim("~/.kubectl-why/decisions") + "\n")
	b.WriteString("\n")
	b.WriteString("  " + ui.Yellow("--lang") + " " + ui.Dim("<code>") + "\n")
	b.WriteString("    Output language: " + ui.Dim("en, ko, ja, zh, es") + "\n")
	b.WriteString("    Default: auto-detected from " + ui.Dim("LC_ALL, LANG") + "\n")
	b.WriteString("    See: " + ui.Cyan("kubectl why help i18n") + "\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("OUTPUT FLAGS") + "\n")
	b.WriteString("\n")
	b.WriteString("  " + ui.Yellow("-o, --output") + " " + ui.Dim("<format>") + "\n")
	b.WriteString("    Format: " + ui.Dim("text, json") + "\n")
	b.WriteString("    Default: " + ui.Dim("text") + "\n")
	b.WriteString("    See: " + ui.Cyan("kubectl why help output") + "\n")
	b.WriteString("\n")
	b.WriteString("  " + ui.Yellow("--no-color") + "\n")
	b.WriteString("    Disable colored output\n")
	b.WriteString("    Also respects " + ui.Dim("NO_COLOR") + " env var\n")
	b.WriteString("\n")
	b.WriteString("  " + ui.Yellow("--quiet") + "\n")
	b.WriteString("    Suppress status messages (scan/AI progress)\n")
	b.WriteString("    Keeps warnings and errors\n")
	b.WriteString("    Auto-disabled when piped\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("SCANNING FLAGS") + " " + ui.Dim("(require external tools)") + "\n")
	b.WriteString("\n")
	b.WriteString("  " + ui.Yellow("--scan") + " " + ui.Dim("<modes>") + "\n")
	b.WriteString("    Enable CVE/SBOM scanners: " + ui.Dim("cve, sbom") + "\n")
	b.WriteString("    Requires: " + ui.Dim("trivy (cve), syft (sbom)") + "\n")
	b.WriteString("    See: " + ui.Cyan("kubectl why help scan") + "\n")
	b.WriteString("\n")
	b.WriteString("  " + ui.Yellow("--scan-timeout") + " " + ui.Dim("<duration>") + "\n")
	b.WriteString("    Scanner timeout (default: " + ui.Dim("10s") + ")\n")
	b.WriteString("\n")
	b.WriteString("  " + ui.Yellow("--require-scan") + "\n")
	b.WriteString("    Exit with error if scanner unavailable\n")
	b.WriteString("    Default: " + ui.Dim("false") + " (warns and continues)\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("AI FLAGS") + " " + ui.Dim("(require API key)") + "\n")
	b.WriteString("\n")
	b.WriteString("  " + ui.Yellow("--ai") + "\n")
	b.WriteString("    Add AI-generated context\n")
	b.WriteString("    Requires: " + ui.Bold(ui.Red("WHY_AI_API_KEY")) + " env var\n")
	b.WriteString("    See: " + ui.Cyan("kubectl why help ai") + "\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("EXAMPLES") + "\n")
	b.WriteString("  kubectl why " + ui.Yellow("--lang ko -o json") + " explain my-app\n")
	b.WriteString("  kubectl why " + ui.Yellow("--scan cve --ai") + " explain my-app\n")
	b.WriteString("  kubectl why " + ui.Yellow("--dir /tmp --no-color") + " decision list\n")
	b.WriteString("\n")
	return b.String()
}

// RenderHelpScan returns detailed help for scanning features.
func RenderHelpScan() string {
	var b strings.Builder
	b.WriteString(ui.Bold(ui.Cyan("CVE and SBOM Scanning")) + "\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("OVERVIEW") + "\n")
	b.WriteString("  kubectl-why works fully offline by default. " + ui.Yellow("--scan") + " is optional.\n")
	b.WriteString("  Attach live CVE/SBOM data from external scanners.\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("SCAN MODES") + "\n")
	b.WriteString("  " + ui.Cyan("cve") + "       Vulnerability scanning (requires " + ui.Dim("trivy") + ")\n")
	b.WriteString("  " + ui.Cyan("sbom") + "      Software Bill of Materials (requires " + ui.Dim("syft") + ")\n")
	b.WriteString("  " + ui.Cyan("cve,sbom") + "  Both scanners\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("INSTALLATION") + "\n")
	b.WriteString("  macOS:  " + ui.Dim("brew install trivy syft") + "\n")
	b.WriteString("  Linux:  See https://trivy.dev and https://github.com/anchore/syft\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("BEHAVIOR") + "\n")
	b.WriteString("  • Missing scanner → " + ui.Yellow("warning") + " and continues (default)\n")
	b.WriteString("  • " + ui.Yellow("--require-scan") + " → exits with error if unavailable\n")
	b.WriteString("  • " + ui.Yellow("--scan-timeout") + " → adjust timeout (default: 10s)\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("EXAMPLES") + "\n")
	b.WriteString("  kubectl why " + ui.Yellow("--scan cve") + " explain my-app\n")
	b.WriteString("  kubectl why " + ui.Yellow("--scan cve,sbom") + " explain my-app\n")
	b.WriteString("  kubectl why " + ui.Yellow("--scan cve --scan-timeout 30s") + " explain my-app\n")
	b.WriteString("  kubectl why " + ui.Yellow("--scan cve --require-scan") + " explain my-app\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("WHEN TO USE") + "\n")
	b.WriteString("  " + ui.Green("✓") + " You want live CVE data attached to decisions\n")
	b.WriteString("  " + ui.Green("✓") + " You need SBOM for compliance/auditing\n")
	b.WriteString("  " + ui.Green("✓") + " CI/CD environment with scanners installed\n")
	b.WriteString("\n")
	b.WriteString("  " + ui.Red("✗") + " Fast, offline analysis (use default mode)\n")
	b.WriteString("  " + ui.Red("✗") + " Scanners not installed\n")
	b.WriteString("  " + ui.Red("✗") + " Just testing or exploring\n")
	b.WriteString("\n")
	b.WriteString(ui.Yellow("NOTE:") + " Tool works fully offline without this flag.\n")
	b.WriteString("      If scanner missing, displays warning and continues.\n")
	b.WriteString("\n")
	return b.String()
}

// RenderHelpAI returns detailed help for AI features.
func RenderHelpAI() string {
	var b strings.Builder
	b.WriteString(ui.Bold(ui.Cyan("AI-Powered Insights")) + "\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("OVERVIEW") + "\n")
	b.WriteString("  kubectl-why provides complete explanations by default.\n")
	b.WriteString("  " + ui.Yellow("--ai") + " adds optional AI-generated context for additional insights.\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("SETUP") + "\n")
	b.WriteString("  1. Get API key from your AI provider\n")
	b.WriteString("  2. Set environment variable:\n")
	b.WriteString("     " + ui.Dim("export") + " " + ui.Bold(ui.Red("WHY_AI_API_KEY")) + "=" + ui.Dim("your-api-key") + "\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("WHAT AI ADDS") + "\n")
	b.WriteString("  • Contextual explanation of why violations matter\n")
	b.WriteString("  • Additional remediation suggestions\n")
	b.WriteString("  • Security best practices cross-reference\n")
	b.WriteString("\n")
	b.WriteString(ui.Yellow("NOTE:") + " Base explanations (violations, evidence, fixes) are always\n")
	b.WriteString("      generated locally. AI is purely optional enhancement.\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("EXAMPLES") + "\n")
	b.WriteString("  kubectl why " + ui.Yellow("--ai") + " explain my-app\n")
	b.WriteString("  kubectl why " + ui.Yellow("--ai --scan cve --lang ko") + " explain my-app\n")
	b.WriteString("  kubectl why " + ui.Yellow("--ai -o json") + " explain my-app\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("BEHAVIOR") + "\n")
	b.WriteString("  • Missing " + ui.Bold(ui.Red("WHY_AI_API_KEY")) + " → exits with error\n")
	b.WriteString("  • AI call fails → " + ui.Yellow("warning") + " and continues without AI\n")
	b.WriteString("  • Timeout: 30s (hard-coded)\n")
	b.WriteString("  • AI output is best-effort\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("WHEN TO USE") + "\n")
	b.WriteString("  " + ui.Green("✓") + " Want context beyond technical violations\n")
	b.WriteString("  " + ui.Green("✓") + " Learning Kubernetes security\n")
	b.WriteString("  " + ui.Green("✓") + " Need security posture suggestions\n")
	b.WriteString("\n")
	b.WriteString("  " + ui.Red("✗") + " Need fast, deterministic output\n")
	b.WriteString("  " + ui.Red("✗") + " Automated CI/CD pipelines\n")
	b.WriteString("  " + ui.Red("✗") + " API key not available\n")
	b.WriteString("\n")
	return b.String()
}

// RenderHelpOutput returns detailed help for output formats.
func RenderHelpOutput() string {
	var b strings.Builder
	b.WriteString(ui.Bold(ui.Cyan("Output Formats")) + "\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("FORMATS") + "\n")
	b.WriteString("  " + ui.Cyan("text") + " (default)  Human-readable with colors\n")
	b.WriteString("  " + ui.Cyan("json") + "           Structured data for automation\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("TEXT FORMAT") + "\n")
	b.WriteString("  Human-readable output with colored sections, violations, and fixes.\n")
	b.WriteString("  Best for interactive terminal use.\n")
	b.WriteString("\n")
	b.WriteString("  Colors:\n")
	b.WriteString("  • Auto-detected based on TTY\n")
	b.WriteString("  • Disabled when piped (e.g., " + ui.Dim("| cat") + ")\n")
	b.WriteString("  • " + ui.Yellow("--no-color") + " to disable\n")
	b.WriteString("  • Respects " + ui.Dim("NO_COLOR") + " env var\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("JSON FORMAT") + "\n")
	b.WriteString("  Structured output with " + ui.Dim("schemaVersion") + " for forward compatibility.\n")
	b.WriteString("\n")
	b.WriteString("  Structure:\n")
	b.WriteString("  " + ui.Dim("{") + "\n")
	b.WriteString("    \"schemaVersion\": \"1.0\",\n")
	b.WriteString("    \"decision\": { \"id\": \"...\", \"violations\": [...], ... }\n")
	b.WriteString("  " + ui.Dim("}") + "\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("EXAMPLES") + "\n")
	b.WriteString("  kubectl why explain my-app\n")
	b.WriteString("  kubectl why " + ui.Yellow("-o json") + " explain my-app\n")
	b.WriteString("  kubectl why " + ui.Yellow("-o json") + " explain my-app | jq '.decision.violations'\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("WHEN TO USE") + "\n")
	b.WriteString("  " + ui.Bold("Text") + " for:\n")
	b.WriteString("  • Interactive terminal use\n")
	b.WriteString("  • Quick debugging\n")
	b.WriteString("  • Learning about violations\n")
	b.WriteString("\n")
	b.WriteString("  " + ui.Bold("JSON") + " for:\n")
	b.WriteString("  • CI/CD integration\n")
	b.WriteString("  • Feeding dashboards\n")
	b.WriteString("  • Database storage\n")
	b.WriteString("  • Processing with jq/Python/Go\n")
	b.WriteString("  • Automated compliance checks\n")
	b.WriteString("\n")
	return b.String()
}

// RenderHelpI18n returns detailed help for internationalization.
func RenderHelpI18n() string {
	var b strings.Builder
	b.WriteString(ui.Bold(ui.Cyan("Language Support (i18n)")) + "\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("SUPPORTED LANGUAGES") + "\n")
	b.WriteString("  " + ui.Cyan("en") + " English (default)  " + ui.Cyan("ja") + " Japanese  " + ui.Cyan("es") + " Spanish\n")
	b.WriteString("  " + ui.Cyan("ko") + " Korean            " + ui.Cyan("zh") + " Chinese (Simplified/Traditional)\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("USAGE") + "\n")
	b.WriteString("  kubectl why " + ui.Yellow("--lang") + " " + ui.Dim("<code>") + " <command>\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("AUTO-DETECTION") + "\n")
	b.WriteString("  If " + ui.Yellow("--lang") + " not specified, detects from:\n")
	b.WriteString("  1. " + ui.Dim("LC_ALL") + " env var\n")
	b.WriteString("  2. " + ui.Dim("LANG") + " env var\n")
	b.WriteString("  3. " + ui.Dim("LANGUAGE") + " env var\n")
	b.WriteString("  Falls back to English if unsupported.\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("WHAT CHANGES") + "\n")
	b.WriteString("  • Explanations and messages\n")
	b.WriteString("  • Section headers (WHY, STATUS, VIOLATIONS)\n")
	b.WriteString("  • Remediation suggestions\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("WHAT STAYS THE SAME") + "\n")
	b.WriteString("  • Field paths: " + ui.Dim("spec.template.spec.containers[0]") + "\n")
	b.WriteString("  • CVE IDs: " + ui.Dim("CVE-2023-1234") + "\n")
	b.WriteString("  • Resource names and namespaces\n")
	b.WriteString("  • JSON keys (remain in English)\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("EXAMPLES") + "\n")
	b.WriteString("  kubectl why " + ui.Yellow("--lang ko") + " explain my-app\n")
	b.WriteString("  kubectl why " + ui.Yellow("--lang ja") + " explain my-app\n")
	b.WriteString("  kubectl why " + ui.Yellow("--lang zh") + " explain my-app\n")
	b.WriteString("  kubectl why " + ui.Yellow("--lang es -o json") + " explain my-app\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("AUTO-DETECT EXAMPLE") + "\n")
	b.WriteString("  " + ui.Dim("export LANG=ko_KR.UTF-8") + "\n")
	b.WriteString("  kubectl why explain my-app  " + ui.Dim("# Automatically uses Korean") + "\n")
	b.WriteString("\n")
	b.WriteString(ui.Bold("WHEN TO USE") + "\n")
	b.WriteString("  • Multilingual teams\n")
	b.WriteString("  • Localized reporting for management\n")
	b.WriteString("  • Educational content in native language\n")
	b.WriteString("  • Compliance docs in local language\n")
	b.WriteString("\n")
	b.WriteString(ui.Yellow("NOTE:") + " All translations built-in. Works fully offline.\n")
	b.WriteString("      No AI required.\n")
	b.WriteString("\n")
	return b.String()
}

// FormatUnknownHelpTopic returns an error message for unknown help topics.
func FormatUnknownHelpTopic(topic string) string {
	return fmt.Sprintf("%s Unknown help topic %q\n\nAvailable topics: %s, %s, %s, %s, %s, %s, %s, %s\nRun 'kubectl why %s' to see all topics.\n\n",
		ui.Red("Error:"), topic,
		ui.Cyan("explain"), ui.Cyan("decision"), ui.Cyan("mock"),
		ui.Cyan("flags"), ui.Cyan("scan"), ui.Cyan("ai"),
		ui.Cyan("output"), ui.Cyan("i18n"),
		ui.Cyan("help"))
}

// FormatUnknownCommand returns an error message for unknown commands.
func FormatUnknownCommand(cmd string) string {
	return fmt.Sprintf("%s Unknown command %q\n\nAvailable commands: %s, %s, %s, %s, %s\nRun 'kubectl why --help' for usage information.\n\n",
		ui.Red("Error:"), cmd, ui.Cyan("explain"), ui.Cyan("decision"), ui.Cyan("mock"), ui.Cyan("help"), ui.Cyan("version"))
}

// FormatInvalidOutputFormat returns an error message for invalid output formats.
func FormatInvalidOutputFormat(format string) string {
	return fmt.Sprintf("%s Invalid output format %q\n\nSupported formats: text, json\nExample: kubectl why explain my-app %s json\n\n",
		ui.Red("Error:"), format, ui.Yellow("-o"))
}

// FormatUnknownDecisionSubcommand returns an error message for unknown decision subcommands.
func FormatUnknownDecisionSubcommand(subcmd string) string {
	return fmt.Sprintf("%s Unknown decision subcommand %q\n\nAvailable subcommands: list, get\nRun 'kubectl why --help' for more information.\n\n",
		ui.Red("Error:"), subcmd)
}

// FormatDecisionNotFound returns an error message when a decision is not found.
func FormatDecisionNotFound(id string) string {
	return fmt.Sprintf("%s Decision %q not found\n\nTip: Use 'kubectl why %s list' to see available decisions",
		ui.Red("Error:"), id, ui.Cyan("decision"))
}

// FormatNoDecisionFound returns an error message when no decision is found for a resource.
func FormatNoDecisionFound(kind, name, namespace string) string {
	return fmt.Sprintf("%s No decision found for %s/%s in namespace %s\n\nTip: Create a mock decision with:\n  kubectl why %s create %s",
		ui.Red("Error:"), kind, name, namespace, ui.Cyan("mock"), name)
}

// FormatJSONNotSupported returns an error message for unsupported JSON output.
func FormatJSONNotSupported() string {
	return fmt.Sprintf("%s JSON output is not yet supported for '%s list'\n\nWorkaround: Use text output (default) or use '%s get <id>' with %s json",
		ui.Red("Error:"), ui.Cyan("decision"), ui.Cyan("decision"), ui.Yellow("-o"))
}

// FormatNoDecisionsWithTip returns a message when no decisions are found, with a helpful tip.
func FormatNoDecisionsWithTip() string {
	return "No decisions found.\n\nTip: Create a mock decision with:\n  kubectl why mock create test-app"
}
